
planning_prompt = {"put": '''You are in the middle of a room. Looking quickly around you, you see a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a countertop 1, a garbagecan 1, a handtowelholder 2, a handtowelholder 1, a sinkbasin 2, a sinkbasin 1, a toilet 1, a toiletpaperhanger 1, and a towelholder 1.\nYour task is to: put some spraybottle on toilet.
sub-task 1: {{'description': 'First I need to find and take a spraybottle', 'reasoning instruction': 'Find and take a spraybottle', 'tool use instruction': None}}
sub-task 2: {{'description': 'Finally, I need to put it on toilet', 'reasoning instruction': 'Go to toilet and put the spraybottle on toilet', 'tool use instruction': None}}
Task: You are in the middle of a room. Looking quickly around you, you see a bathtubbasin 1, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a countertop 1, a drawer 4, a drawer 3, a drawer 2, a drawer 1, a dresser 1, a garbagecan 1, a handtowelholder 1, a sinkbasin 2, a sinkbasin 1, a toilet 1, a toiletpaperhanger 1, and a towelholder 1.\nYour task is to: put a soapbottle in garbagecan.
sub-task 1: {{'description': 'First I need to find and take a soapbottle', 'reasoning instruction': 'Find and take a soapbottle', 'tool use instruction': None}}
sub-task 2: {{'description': 'Finally, I need to put it in garbagecan', 'reasoning instruction': 'Go to garbagecan and put the soapbottle in garbagecan', 'tool use instruction': None}}''',
                   "clean": '''You are in the middle of a room.  Looking quickly around you, you see a cabinet 13, a cabinet 12, a cabinet 11, a cabinet 10, a cabinet 9, a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 1, a diningtable 1, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a shelf 3, a shelf 2, a shelf 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1. \nYour task is to: put a clean lettuce in diningtable. 
sub-task 1: {{'description': 'First I need to find and take a lettuce', 'reasoning instruction': 'Find and take a lettuce', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to clean it with sinkbasin', 'reasoning instruction': 'Clean the lettuce with sinkbasin', 'tool use instruction': None}}
sub-task 3: {{'description': 'Finally, I need to put it in diningtable', 'reasoning instruction': 'Go to diningtable and put the lettuce in diningtable', 'tool use instruction': None}}
Task: You are in the middle of a room. Looking quickly around you, you see a bathtubbasin 1, a garbagecan 1, a handtowelholder 1, a shelf 3, a shelf 2, a shelf 1, a sinkbasin 1, a toilet 1, a toiletpaperhanger 1, and a towelholder 1.\nYour task is to: clean some soapbar and put it in toilet.
sub-task 1: {{'description': 'First I need to find and take a soapbar', 'reasoning instruction': 'Find and take a soapbar', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to clean it with sinkbasin', 'reasoning instruction': 'Clean the soapbar with sinkbasin', 'tool use instruction': None}}
sub-task 3: {{'description': 'Finally, I need to put it in toilet', 'reasoning instruction': 'Go to toilet and put the soapbar in toilet', 'tool use instruction': None}}''',
                   "heat": '''You are in the middle of a room.  Looking quickly around you, you see a cabinet 10, a cabinet 9, a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 3, a countertop 2, a countertop 1, a diningtable 1, a drawer 6, a drawer 5, a drawer 4, a drawer 3, a drawer 2, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1. \nYour task is to: heat some egg and put it in diningtable.
sub-task 1: {{'description': 'First I need to find and take an egg', 'reasoning instruction': 'Find and take an egg', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to heat it with microwave', 'reasoning instruction': 'Heat the egg with microwave', 'tool use instruction': None}}
sub-task 3: {{'description': 'Finally, I need to put it in diningtable', 'reasoning instruction': 'Go to diningtable and put the egg in diningtable', 'tool use instruction': None}}
Task: You are in the middle of a room. Looking quickly around you, you see a cabinet 13, a cabinet 12, a cabinet 11, a cabinet 10, a cabinet 9, a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 1, a diningtable 1, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a shelf 3, a shelf 2, a shelf 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1.\nYour task is to: put a hot apple in fridge.
sub-task 1: {{'description': 'First I need to find and take a apple', 'reasoning instruction': 'Find and take a apple', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to heat it with microwave', 'reasoning instruction': 'Heat the apple with microwave', 'tool use instruction': None}}
sub-task 3: {{'description': 'Finally, I need to put it in fridge', 'reasoning instruction': 'Go to fridge and put the apple in fridge', 'tool use instruction': None}}''',
                   "cool": '''You are in the middle of a room.  Looking quickly around you, you see a cabinet 16, a cabinet 15, a cabinet 14, a cabinet 13, a cabinet 12, a cabinet 11, a cabinet 10, a cabinet 9, a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 2, a countertop 1, a diningtable 1, a drawer 5, a drawer 4, a drawer 3, a drawer 2, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a safe 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2,  a stoveburner 1, and a toaster 1. \nYour task is to: cool some pan and put it in stoveburner.
sub-task 1: {{'description': 'First I need to find and take a pan', 'reasoning instruction': 'Find and take a pan', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to cool it with fridge', 'reasoning instruction': 'Cool the pan with fridge', 'tool use instruction': None}}
sub-task 3: {{'description': 'Finally, I need to put it in stoveburner', 'reasoning instruction': 'Go to stoveburner and put the pan in stoveburner', 'tool use instruction': None}}
Task: You are in the middle of a room. Looking quickly around you, you see a cabinet 12, a cabinet 11, a cabinet 10, a cabinet 9, a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 2, a countertop 1, a diningtable 1, a drawer 3, a drawer 2, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1.\nYour task is to: cool some potato and put it in diningtable.
sub-task 1: {{'description': 'First I need to find and take a potato', 'reasoning instruction': 'Find and take a potato', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to cool it with fridge', 'reasoning instruction': 'Cool the potato with fridge', 'tool use instruction': None}}
sub-task 3: {{'description': 'Finally, I need to put it in diningtable', 'reasoning instruction': 'Go to diningtable and put the potato in diningtable', 'tool use instruction': None}}''',
                   "puttwo": '''You are in the middle of a room.  Looking quickly around you, you see a armchair 2, a armchair 1, a bed 1, a countertop 1, a diningtable 1, a drawer 2, a drawer 1, a dresser 1, a garbagecan 1, a laundryhamper 1, and a sidetable 1. \nYour task is to: put two creditcard in dresser.
sub-task 1: {{'description': 'First I need to find and take the first creditcard', 'reasoning instruction': 'Find and take the first creditcard', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to put it in dresser', 'reasoning instruction': 'Go to dresser and put the first creditcard in dresser', 'tool use instruction': None}}
sub-task 3: {{'description': 'Then, I need to find and take the second creditcard', 'reasoning instruction': 'Find and take the second creditcard', 'tool use instruction': None}}
sub-task 4: {{'description': 'Finally, I need to put the second creditcard in dresser', 'reasoning instruction': 'Go to dresser and put the second creditcard in dresser', 'tool use instruction': None}}
Task: You are in the middle of a room. Looking quickly around you, you see a cabinet 20, a cabinet 19, a cabinet 18, a cabinet 17, a cabinet 16, a cabinet 15, a cabinet 14, a cabinet 13, a cabinet 12, a cabinet 11, a cabinet 10, a cabinet 9, a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 3, a countertop 2, a countertop 1, a drawer 3, a drawer 2, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a shelf 3, a shelf 2, a shelf 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1.\nYour task is to: put two saltshaker in drawer.
sub-task 1: {{'description': 'First I need to find and take the first saltshaker', 'reasoning instruction': 'Find and take the first saltshaker', 'tool use instruction': None}}
sub-task 2: {{'description': 'Next, I need to put it in drawer', 'reasoning instruction': 'Go to drawer and put the first saltshaker in drawer', 'tool use instruction': None}}
sub-task 3: {{'description': 'Then, I need to find and take the second saltshaker', 'reasoning instruction': 'Find and take the second saltshaker', 'tool use instruction': None}}
sub-task 4: {{'description': 'Finally, I need to put the second saltshaker in drawer', 'reasoning instruction': 'Go to drawer and put the second saltshaker in drawer', 'tool use instruction': None}}''',
                   "examine": '''You are in the middle of a room.  Looking quickly around you, you see a bed 1, a desk 1, a drawer 3, a drawer 2, a drawer 1, a garbagecan 1, a safe 1, a shelf 5, a shelf 4, a shelf 3, a shelf 2, a shelf 1, a sidetable 2, and a sidetable 1. \nYour task is to: look at bowl under the desklamp.
sub-task 1: {{'description': 'First I need to find and take a bowl', 'reasoning instruction': 'Find and take a bowl', 'tool use instruction': None}}
sub-task 2: {{'description': 'Finally, I need to find and use a desklamp', 'reasoning instruction': 'Find and use a desklamp', 'tool use instruction': None}}
Task: You are in the middle of a room. Looking quickly around you, you see a coffeetable 1, a diningtable 1, a drawer 4, a drawer 3, a drawer 2, a drawer 1, a dresser 1, a garbagecan 1, a sidetable 2, a sidetable 1, and a sofa 1.\nYour task is to: look at statue under the desklamp.
sub-task 1: {{'description': 'First I need to find and take a statue', 'reasoning instruction': 'Find and take a statue', 'tool use instruction': None}}
sub-task 2: {{'description': 'Finally, I need to find and use a desklamp', 'reasoning instruction': 'Find and use a desklamp', 'tool use instruction': None}}'''}
                   
